version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-cool-mud-a2ypb623.eu-central-1.pg.koyeb.app/koyebdb
      - SPRING_DATASOURCE_USERNAME=koyeb-adm
      - SPRING_DATASOURCE_PASSWORD=npg_lRVtf7E3MKwa
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge